### ISSUE TITLE
Define clear MVP for coming sprint

### ISSUE THREAD

**Issue by zazzzi** [JohnForslundGebka/gbgame#28]
We need to have a clear "road-map" that defines the steps that we want to have "finished" at certain points. 

AC:
- Define different stages for our products that can be presented as MVPs. 
- Decide what our MVP can be for the finished product could be.

**Comment by JohnForslundGebka** [comment]
see general planning info on figma for MVP road map

https://www.figma.com/file/qXugChYDWrAmf3KyWO1ABr/General-planning-info?type=whiteboard&node-id=211-407&t=eFyxMSz1Td4orJIM-0
